{
  "Header": {
    "Original": "CVE-2018-1000117 (Python Software Foundation CPython version From 3.2 until 3.6.4 on Win ...)",
    "Line": 360597,
    "ID": "CVE-2018-1000117",
    "Description": "(Python Software Foundation CPython version From 3.2 until 3.6.4 on Win ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.7 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 360598,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.6 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 360599,
      "Type": "package",
      "Package": "python3.6",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.5 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 360600,
      "Type": "package",
      "Package": "python3.5",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.4 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 360601,
      "Type": "package",
      "Package": "python3.4",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python2.7 \u003cnot-affected\u003e (os.symlink for Windows introduced in 3.2)",
      "Line": 360602,
      "Type": "package",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "os.symlink for Windows introduced in 3.2"
    },
    {
      "Original": "NOTE: http://hg.python.org/lookup/6921e73e33edc3c61bc2d78ed558eaa22a89a564",
      "Line": 360603,
      "Type": "NOTE",
      "Description": "http://hg.python.org/lookup/6921e73e33edc3c61bc2d78ed558eaa22a89a564"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue33001",
      "Line": 360604,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue33001"
    }
  ]
}