{
  "Header": {
    "Original": "CVE-2023-25399 (A refcounting issue which leads to potential memory leak was discovere ...)",
    "Line": 24635,
    "ID": "CVE-2023-25399",
    "Description": "(A refcounting issue which leads to potential memory leak was discovere ...)"
  },
  "Annotations": [
    {
      "Original": "- scipy 1.10.0-2",
      "Line": 24636,
      "Type": "package",
      "Package": "scipy",
      "Kind": "fixed",
      "Version": "1.10.0-2"
    },
    {
      "Original": "NOTE: https://github.com/scipy/scipy/issues/16235",
      "Line": 24637,
      "Type": "NOTE",
      "Description": "https://github.com/scipy/scipy/issues/16235"
    },
    {
      "Original": "NOTE: https://github.com/scipy/scipy/pull/16397",
      "Line": 24638,
      "Type": "NOTE",
      "Description": "https://github.com/scipy/scipy/pull/16397"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/scipy/scipy/commit/9b6521198c4f31d3f9cb525e581bea8e3e77f0a2 (v1.10.0rc1)",
      "Line": 24639,
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/scipy/scipy/commit/9b6521198c4f31d3f9cb525e581bea8e3e77f0a2 (v1.10.0rc1)"
    },
    {
      "Original": "NOTE: http://www.square16.org/achievement/cve-2023-25399/",
      "Line": 24640,
      "Type": "NOTE",
      "Description": "http://www.square16.org/achievement/cve-2023-25399/"
    }
  ]
}