{
  "Header": {
    "Original": "CVE-2019-14888 (A vulnerability was found in the Undertow HTTP server in versions befo ...)",
    "Line": 281991,
    "ID": "CVE-2019-14888",
    "Description": "(A vulnerability was found in the Undertow HTTP server in versions befo ...)"
  },
  "Annotations": [
    {
      "Original": "- undertow 2.0.30-1",
      "Line": 281992,
      "Type": "package",
      "Package": "undertow",
      "Kind": "fixed",
      "Version": "2.0.30-1"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1772464",
      "Line": 281993,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1772464"
    },
    {
      "Original": "NOTE: https://issues.redhat.com/browse/UNDERTOW-1623",
      "Line": 281994,
      "Type": "NOTE",
      "Description": "https://issues.redhat.com/browse/UNDERTOW-1623"
    },
    {
      "Original": "NOTE: https://github.com/undertow-io/undertow/commit/846c50ead09f7d0b38965b4726ba0b6c5582bf7f (and followups)",
      "Line": 281995,
      "Type": "NOTE",
      "Description": "https://github.com/undertow-io/undertow/commit/846c50ead09f7d0b38965b4726ba0b6c5582bf7f (and followups)"
    },
    {
      "Original": "NOTE: https://github.com/undertow-io/undertow/pull/828",
      "Line": 281996,
      "Type": "NOTE",
      "Description": "https://github.com/undertow-io/undertow/pull/828"
    },
    {
      "Original": "NOTE: https://github.com/undertow-io/undertow/pull/852",
      "Line": 281997,
      "Type": "NOTE",
      "Description": "https://github.com/undertow-io/undertow/pull/852"
    }
  ]
}