{
  "Header": {
    "Original": "CVE-2017-5992 (Openpyxl 2.4.1 resolves external entities by default, which allows rem ...)",
    "Line": 414170,
    "ID": "CVE-2017-5992",
    "Description": "(Openpyxl 2.4.1 resolves external entities by default, which allows rem ...)"
  },
  "Annotations": [
    {
      "Original": "- openpyxl 2.3.0-3 (bug #854442)",
      "Line": 414171,
      "Type": "package",
      "Package": "openpyxl",
      "Kind": "fixed",
      "Version": "2.3.0-3",
      "BugNo": 854442
    },
    {
      "Original": "[jessie] - openpyxl \u003cnot-affected\u003e (vulnerable code not present)",
      "Line": 414172,
      "Type": "package",
      "Release": "jessie",
      "Package": "openpyxl",
      "Kind": "not-affected",
      "Description": "vulnerable code not present"
    },
    {
      "Original": "[wheezy] - openpyxl \u003cnot-affected\u003e (vulnerable code not present)",
      "Line": 414173,
      "Type": "package",
      "Release": "wheezy",
      "Package": "openpyxl",
      "Kind": "not-affected",
      "Description": "vulnerable code not present"
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2017/02/07/5",
      "Line": 414174,
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2017/02/07/5"
    },
    {
      "Original": "NOTE: https://bitbucket.org/openpyxl/openpyxl/issues/749",
      "Line": 414175,
      "Type": "NOTE",
      "Description": "https://bitbucket.org/openpyxl/openpyxl/issues/749"
    },
    {
      "Original": "NOTE: https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1",
      "Line": 414176,
      "Type": "NOTE",
      "Description": "https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1"
    }
  ]
}