{
  "Header": {
    "Original": "CVE-2020-8492 (Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7  ...)",
    "Line": 248269,
    "ID": "CVE-2020-8492",
    "Description": "(Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3432-1 DLA-2280-1}",
      "Line": 248270,
      "Type": "xref",
      "Bugs": [
        "DLA-3432-1",
        "DLA-2280-1"
      ]
    },
    {
      "Original": "- python3.8 3.8.3~rc1-1",
      "Line": 248271,
      "Type": "package",
      "Package": "python3.8",
      "Kind": "fixed",
      "Version": "3.8.3~rc1-1"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e",
      "Line": 248272,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed"
    },
    {
      "Original": "[buster] - python3.7 3.7.3-2+deb10u2",
      "Line": 248273,
      "Type": "package",
      "Release": "buster",
      "Package": "python3.7",
      "Kind": "fixed",
      "Version": "3.7.3-2+deb10u2"
    },
    {
      "Original": "- python3.5 \u003cremoved\u003e",
      "Line": 248274,
      "Type": "package",
      "Package": "python3.5",
      "Kind": "removed"
    },
    {
      "Original": "- python3.4 \u003cremoved\u003e",
      "Line": 248275,
      "Type": "package",
      "Package": "python3.4",
      "Kind": "removed"
    },
    {
      "Original": "[jessie] - python3.4 \u003cpostponed\u003e (Minor issue)",
      "Line": 248276,
      "Type": "package",
      "Release": "jessie",
      "Package": "python3.4",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "- python2.7 2.7.18-2 (low; bug #970099)",
      "Line": 248277,
      "Type": "package",
      "Package": "python2.7",
      "Kind": "fixed",
      "Version": "2.7.18-2",
      "Severity": "low",
      "BugNo": 970099
    },
    {
      "Original": "[jessie] - python2.7 \u003cno-dsa\u003e (Minor issue)",
      "Line": 248278,
      "Type": "package",
      "Release": "jessie",
      "Package": "python2.7",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue39503",
      "Line": 248279,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue39503"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/18284",
      "Line": 248280,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/18284"
    },
    {
      "Original": "NOTE: https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html",
      "Line": 248281,
      "Type": "NOTE",
      "Description": "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/0b297d4ff1c0e4480ad33acae793fbaf4bf015b4 (master)",
      "Line": 248282,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/0b297d4ff1c0e4480ad33acae793fbaf4bf015b4 (master)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/ea9e240aa02372440be8024acb110371f69c9d41 (3.8-branch)",
      "Line": 248283,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/ea9e240aa02372440be8024acb110371f69c9d41 (3.8-branch)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/b57a73694e26e8b2391731b5ee0b1be59437388e (3.7-branch)",
      "Line": 248284,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/b57a73694e26e8b2391731b5ee0b1be59437388e (3.7-branch)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/69cdeeb93e0830004a495ed854022425b93b3f3e (3.6-branch)",
      "Line": 248285,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/69cdeeb93e0830004a495ed854022425b93b3f3e (3.6-branch)"
    }
  ]
}