{
  "Header": {
    "Original": "CVE-2018-10928 (A flaw was found in RPC request using gfs3_symlink_req in glusterfs se ...)",
    "Line": 352276,
    "ID": "CVE-2018-10928",
    "Description": "(A flaw was found in RPC request using gfs3_symlink_req in glusterfs se ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2806-1 DLA-1510-1}",
      "Line": 352277,
      "Type": "xref",
      "Bugs": [
        "DLA-2806-1",
        "DLA-1510-1"
      ]
    },
    {
      "Original": "- glusterfs 4.1.4-1 (bug #909215)",
      "Line": 352278,
      "Type": "package",
      "Package": "glusterfs",
      "Kind": "fixed",
      "Version": "4.1.4-1",
      "BugNo": 909215
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1612659",
      "Line": 352279,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1612659"
    },
    {
      "Original": "NOTE: https://github.com/gluster/glusterfs/commit/9ae986f18c0f251cba6bbc23eae2150a8ce0417e",
      "Line": 352280,
      "Type": "NOTE",
      "Description": "https://github.com/gluster/glusterfs/commit/9ae986f18c0f251cba6bbc23eae2150a8ce0417e"
    },
    {
      "Original": "NOTE: When fixing this issue make sure to be complete an not open CVE-2018-14651",
      "Line": 352281,
      "Type": "NOTE",
      "Description": "When fixing this issue make sure to be complete an not open CVE-2018-14651"
    }
  ]
}