{
  "Header": {
    "Original": "CVE-2021-3514 (When using a sync_repl client in 389-ds-base, an authenticated attacke ...)",
    "Line": 156882,
    "ID": "CVE-2021-3514",
    "Description": "(When using a sync_repl client in 389-ds-base, an authenticated attacke ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3399-1}",
      "Line": 156883,
      "Type": "xref",
      "Bugs": [
        "DLA-3399-1"
      ]
    },
    {
      "Original": "- 389-ds-base 1.4.4.11-2 (bug #988727)",
      "Line": 156884,
      "Type": "package",
      "Package": "389-ds-base",
      "Kind": "fixed",
      "Version": "1.4.4.11-2",
      "BugNo": 988727
    },
    {
      "Original": "[stretch] - 389-ds-base \u003cno-dsa\u003e (Minor issue)",
      "Line": 156885,
      "Type": "package",
      "Release": "stretch",
      "Package": "389-ds-base",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/issues/4711",
      "Line": 156886,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/issues/4711"
    }
  ]
}