{
  "Header": {
    "Original": "CVE-2013-6418 (PyWBEM 0.7 and earlier uses a separate connection to validate X.509 ce ...)",
    "Line": 517402,
    "ID": "CVE-2013-6418",
    "Description": "(PyWBEM 0.7 and earlier uses a separate connection to validate X.509 ce ...)"
  },
  "Annotations": [
    {
      "Original": "- pywbem 0.8.0~dev650-1 (low; bug #732594)",
      "Line": 517403,
      "Type": "package",
      "Package": "pywbem",
      "Kind": "fixed",
      "Version": "0.8.0~dev650-1",
      "Severity": "low",
      "BugNo": 732594
    },
    {
      "Original": "[squeeze] - pywbem \u003cno-dsa\u003e (Minor issue)",
      "Line": 517404,
      "Type": "package",
      "Release": "squeeze",
      "Package": "pywbem",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[wheezy] - pywbem \u003cno-dsa\u003e (Minor issue)",
      "Line": 517405,
      "Type": "package",
      "Release": "wheezy",
      "Package": "pywbem",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: fix: https://bugzilla.redhat.com/attachment.cgi?id=851357",
      "Line": 517406,
      "Type": "NOTE",
      "Description": "fix: https://bugzilla.redhat.com/attachment.cgi?id=851357"
    }
  ]
}