{
  "Header": {
    "Original": "CVE-2019-3858 (An out of bounds read flaw was discovered in libssh2 before 1.8.1 when ...)",
    "Line": 313042,
    "ID": "CVE-2019-3858",
    "Description": "(An out of bounds read flaw was discovered in libssh2 before 1.8.1 when ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4431-1 DLA-1730-1}",
      "Line": 313043,
      "Type": "xref",
      "Bugs": [
        "DSA-4431-1",
        "DLA-1730-1"
      ]
    },
    {
      "Original": "- libssh2 1.8.0-2.1 (bug #924965)",
      "Line": 313044,
      "Type": "package",
      "Package": "libssh2",
      "Kind": "fixed",
      "Version": "1.8.0-2.1",
      "BugNo": 924965
    },
    {
      "Original": "NOTE: https://libssh2.org/CVE-2019-3858.html",
      "Line": 313045,
      "Type": "NOTE",
      "Description": "https://libssh2.org/CVE-2019-3858.html"
    },
    {
      "Original": "NOTE: Patch: https://libssh2.org/1.8.0-CVE/CVE-2019-3858.patch",
      "Line": 313046,
      "Type": "NOTE",
      "Description": "Patch: https://libssh2.org/1.8.0-CVE/CVE-2019-3858.patch"
    },
    {
      "Original": "NOTE: https://github.com/libssh2/libssh2/pull/316",
      "Line": 313047,
      "Type": "NOTE",
      "Description": "https://github.com/libssh2/libssh2/pull/316"
    }
  ]
}