{
  "Header": {
    "Original": "CVE-2021-3629 (A flaw was found in Undertow. A potential security issue in flow contr ...)",
    "Line": 148607,
    "ID": "CVE-2021-3629",
    "Description": "(A flaw was found in Undertow. A potential security issue in flow contr ...)"
  },
  "Annotations": [
    {
      "Original": "- undertow 2.2.12-1 (bug #1016448)",
      "Line": 148608,
      "Type": "package",
      "Package": "undertow",
      "Kind": "fixed",
      "Version": "2.2.12-1",
      "BugNo": 1016448
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1977362",
      "Line": 148609,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1977362"
    },
    {
      "Original": "NOTE: Make sure to also address followup tracked as CVE-2022-1259:",
      "Line": 148610,
      "Type": "NOTE",
      "Description": "Make sure to also address followup tracked as CVE-2022-1259:"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2072339",
      "Line": 148611,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2072339"
    }
  ]
}