{
  "Header": {
    "Original": "CVE-2016-1902 (The nextBytes function in the SecureRandom class in Symfony before 2.3 ...)",
    "Line": 458273,
    "ID": "CVE-2016-1902",
    "Description": "(The nextBytes function in the SecureRandom class in Symfony before 2.3 ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-3588-1}",
      "Line": 458274,
      "Type": "xref",
      "Bugs": [
        "DSA-3588-1"
      ]
    },
    {
      "Original": "- symfony 2.7.9+dfsg-1",
      "Line": 458275,
      "Type": "package",
      "Package": "symfony",
      "Kind": "fixed",
      "Version": "2.7.9+dfsg-1"
    },
    {
      "Original": "NOTE: http://symfony.com/blog/cve-2016-1902-securerandom-s-fallback-not-secure-when-openssl-fails",
      "Line": 458276,
      "Type": "NOTE",
      "Description": "http://symfony.com/blog/cve-2016-1902-securerandom-s-fallback-not-secure-when-openssl-fails"
    },
    {
      "Original": "NOTE: https://github.com/symfony/symfony/pull/17359",
      "Line": 458277,
      "Type": "NOTE",
      "Description": "https://github.com/symfony/symfony/pull/17359"
    }
  ]
}